import type { NextPage } from 'next';
import Head from 'next/head';
import { memo } from 'react';
import { Hero, Hexagon, Navbar } from '../src/_components';

// eslint-disable-next-line react/display-name
const Home: NextPage = memo(() => {
  // const handleContext = useCallback((event: EventHandler) => {
  //     event.preventDefault();
  //     event.stopPropagation();
  // }, []);
  // onContextMenu={handleContext}

  return (
    <div className="body">
      <Head>
        <title>Goodnews Ogechukwu Ike | Front-End Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script> */}
        <meta property="og:url" content="https://goodnewsike.com/" />
        <meta property="og:title" content="Goodnews Ike Portfolio Website" />
        <meta property="og:description" content="Goodnews Ike Portfolio Website, developer portfolio, frontend portfolio" />
        <meta property="og:type" content="website" />
      </Head>

      <Navbar />
      <main className="container-fluid wrapper position-relative">
        <Hexagon />
        <Hero />
      </main>

      {/* <div className="socialHandles h-100 position-fixed d-flex align-items-center justify-content-center">
        <ul className="social__handles">
          {socialHandles.map<JSX.Element>((item: NavMap) => (
            <a
              key={`socialHandle__fullScreen-${item.id}`}
              href={item.link}
              target="_blank"
              rel="noreferrer"
              className="my-3">
              <li className="">
                {item.icon}
              </li>
            </a>
          ))}
        </ul>
      </div> */}
    </div>
  );
});

export default Home;
