import type { NextPage } from 'next';
import Head from 'next/head';
import { EventHandler, useCallback, useRef, useState } from 'react';
// import Image from 'next/image';
// import '../styles/Home.module.scss';
import classNames from 'classnames';
import { MenuMap, NavMap } from '../model';
import FullscreenModal from '../_components/Modal';
import { Contact, Experience, Expertise, Work } from '../_sections';
import { Hexagon, menuDrop, socialHandles, useOnClickOutside } from '../_components';

import { GoHome } from 'react-icons/go';

const Home: NextPage = () => {
  const dropdownRef = useRef<null>(null);
  const [dropdown, setDropdown] = useState<boolean>(false);
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const [activeSection, setActiveSection] = useState<number | null>(null);

  const handleActiveSection = (item: number) => {
    setActiveSection(item);
    setModalOpen(true);
    setDropdown(false);
  };

  const handleCloseModal = () => {
    setActiveSection(null);
    setModalOpen(false);
  }

  useOnClickOutside(dropdownRef, () => {
    if (dropdown) setDropdown(false);
  });

  // const handleContext = useCallback((event: EventHandler) => {
  //     event.preventDefault();
  //     event.stopPropagation();
  // }, []);
  // onContextMenu={handleContext}

  return (
    <div className="">
      <Head>
        <title>Goodnews Ike | Software Front-end Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script> */}
      </Head>

      <section className="container-fluid wrapper position-relative">
        <Hexagon />
        <div className="container p-0">
          <div className="hero__section">
            <nav className="container py-4 px-0 d-flex align-items-center justify-content-between">
              <div className="menu position-relative d-flex align-items-center">
                <div
                  ref={dropdownRef}
                  onClick={() => setDropdown((t) => !t)}
                  className={classNames("logo", { active: dropdown })}>
                  <div className="menuToggle me-3"></div>
                  <span className="text-uppercase">menu</span>
                  <ul className={classNames("menu__dropdown position-absolute", {'d-none': !dropdown})}>
                    {menuDrop.map<JSX.Element>((item: MenuMap) => (
                      <li key={`menuDropItem-${item.id}`}
                        onClick={() => handleActiveSection(item.active)}
                        className="text-uppercase">
                        <span className="icon"></span>
                        <span className="label">{item.label}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
              <ul className="social__handles">
                {socialHandles.map<JSX.Element>((item: NavMap) => (
                  <a
                    key={`socialHandle-${item.id}`}
                    href={item.link}
                    target="_blank"
                    rel="noreferrer"
                    className="ms-5">
                    <li className="">
                      {item.icon}
                    </li>
                  </a>
                ))}
              </ul>
            </nav>
            <div className="welcome d-flex flex-column align-items-center justify-content-center">
              <p className="intro">Hello, I&apos;m</p>
              <h1 className="name pt-3 text-uppercase">goodnews ike</h1>
              <h5 className="occupation text-uppercase py-2">Front-end Software Engineer</h5>
              <p className="description py-3 text-center">
                My job is to develop inspiring and exceptionally
                beautiful user experience for your organization
                so that you can attract more clients/partners
                and achieve your goal in time.
              </p>
              <button onClick={() => handleActiveSection(4)} className="mt-4 text-uppercase">hire me</button>
            </div>
          </div>
        </div>
      </section>

      <FullscreenModal open={modalOpen} onClickAway={() => { }} className="screen__modal">
        <Expertise activeSection={activeSection} />
        <Work activeSection={activeSection} />
        <Experience activeSection={activeSection} />
        <Contact activeSection={activeSection} />
        <div className="home__menu h-100 position-fixed d-flex align-items-center justify-content-center">
          <ul className="menu__dropdown d-flex flex-column">
            <li onClick={handleCloseModal}
              className="text-uppercase py-3 position-relative">
              <span className="icon"><GoHome className="home__icon" /></span>
              <span className="label">home</span>
            </li>
            {menuDrop.map<JSX.Element>((item: MenuMap) => (
              <li key={`menuDropItem__fullScreen-${item.id}`}
                onClick={() => handleActiveSection(item.active)}
                className={classNames("text-uppercase py-3 position-relative", {active: item.id === activeSection})}>
                <span className="icon">{item.icon}</span>
                <span className="label">{item.label}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="socialHandles h-100 position-fixed d-flex align-items-center justify-content-center">
          <ul className="social__handles">
            {socialHandles.map<JSX.Element>((item: NavMap) => (
              <a
                key={`socialHandle__fullScreen-${item.id}`}
                href={item.link}
                target="_blank"
                rel="noreferrer"
                className="my-3">
                <li className="">
                  {item.icon}
                </li>
              </a>
            ))}
          </ul>
        </div>
      </FullscreenModal>
    </div>
  )
}

export default Home;
